// Menyudagi har bir bandga mos emoji tanlaydi — key/label kalit so'zlariga qarab.
// Aniq mos kelmasa, guruh nomiga qarab umumiy emoji qo'yiladi (hammasi qamrab olinadi).

const RULES = [
  // ── Boshqaruv & HR bo'limidagi bo'sh qolgan bandlar ──
  [/\brules\b|tartib-qoida/, '📜'],
  [/work-hours|ish vaqti/, '⏰'],
  [/\btenure\b|ish staji/, '🕰️'],
  [/int-jobs|ichki vakansi/, '🧭'],
  [/turnover|kadrlar aylan/, '🔄'],
  [/exit-int|chiqish suhbat/, '🚪'],
  [/\bokr\b/, '🎯'],
  [/insurance|sug'urta|ustoz boshqaruvi/, '🛡️'],
  [/scholarship|stipendiya/, '🎓'],
  [/overtime|qo'shimcha ish/, '⏱️'],
  [/travel-request|xizmat safari/, '✈️'],

  // ── Tizim & IT bo'limidagi bo'sh qolgan bandlar ──
  [/resource-files|resurs markazi|fayl bosh|fayl boshqaruv/, '📁'],
  [/maintenance|ta'mir|tamir/, '🔧'],
  [/network-monitoring|tarmoq\b|uptime|\bsla\b/, '🌐'],
  [/\bbugs\b|bug-report|xatolar|funksiya so'rov|feature-request/, '🐛'],
  [/api-|integratsi|anti-cheat|anticheat/, '🔌'],
  [/import-export|data-import|data-export/, '🔃'],
  [/migrat|webhook/, '🔗'],
  [/system-update|tizim yangilan/, '🆕'],
  [/template|shablon/, '📑'],
  [/faollik & tizim log|activity-log|api-usage/, '🧾'],
  [/boshqa funksiya/, '🔹'],
  [/cleaning|tozalash jadval/, '🧹'],
  [/innov|innovatsiya/, '💡'],
  [/franchise|franshiza/, '🏪'],
  [/theme\b|tema sozlash/, '🎨'],
  [/social-share|ijtimoiy ulashish/, '📤'],
  [/study_groups|study guruh/, '👥'],
  [/subscription-boxes|obuna quti/, '📦'],

  // ── Aloqa & Gamifikatsiya bo'limidagi bandlar ──
  [/media-center|media markazi/, '🎬'],
  [/evt-tickets|tadbir bilet/, '🎟️'],
  [/\bevents\b|tadbirlar markazi/, '🎉'],
  [/promo|daily-bonus|kunlik bonus/, '🎁'],
  [/blog|ijtimoiy platforma|student-posts/, '✍️'],
  [/mystery-box/, '🎲'],
  [/meetings-n|yig'ilish qaror/, '🤝'],
  [/int-ann|ichki e'lon/, '📢'],
  [/roleplay|rol o'yini/, '🎭'],
  [/coin-bank/, '🏦'],
  [/coin-gift/, '🎁'],
  [/avatar-shop|avatar shop/, '👤'],
  [/seasonal|mavsumiy tadbir/, '🎊'],
  [/countdown/, '⏳'],
  [/karaoke/, '🎤'],
  [/voice-msg|ovozli xabar/, '🔊'],
  [/story-menu|\bstory\b/, '📸'],
  [/virtual-room|virtual xona/, '🕶️'],
  [/daily-puzzle|kunlik topishmoq/, '🧩'],
  [/boss-fight/, '⚔️'],
  [/fitness/, '💪'],
  [/stocks\b|stock-game|aksiya o'yini/, '📈'],

  [/video|live-classroom|live-stream|live_sessions|demo-lessons|webinar/, '🎥'],
  [/chat|messages|xabar|internal-chat/, '💬'],
  [/support|complain|shikoyat|feedback|help-desk|ticket/, '🎧'],
  [/ai-|aiassistant|aiaudit/, '🤖'],
  [/certificate|sertifikat|diploma/, '🏆'],
  [/award|badge|mukofot|medal|trophy|leaderboard|top100|hall-of-fame|hall-fame|mvp|employee-of-month|eom\b/, '🏅'],
  [/coin|teacher-coin/, '🪙'],
  [/payment|to'lov|tolov|kassa|cashbox|bank|moliya|salary|oylik|expense|xarajat|invoice|discount|budget|finance|debt|qarz|tax|soliq|reimburse|advance|petty-cash|revenue/, '💰'],
  [/report|hisobot|analytics|analitika|dashboard|kpi|stats|performance-metrics/, '📊'],
  [/calendar|kalendar|jadval|schedule|booking|reservation|room-booking/, '📅'],
  [/exam|test|imtihon|quiz|placement|mock-exam/, '📝'],
  [/security|xavfsiz|audit|password|parol|roles|access-control|key-management|cctv/, '🔒'],
  [/settings|sozlama|theme/, '⚙️'],
  [/branch|filial|building|rooms\b/, '🏢'],
  [/hr\b|xodim|staff|employee|hiring|recruitment|position|lavozim|contract|shartnoma/, '👔'],
  [/leave|tatil|sick|vacation/, '🌴'],
  [/library|kutubxona|book|e_library|elibrary/, '📚'],
  [/attendance|davomat|check-in|checkin/, '✅'],
  [/document|hujjat|legal/, '📄'],
  [/marketing|campaign|lead|crm|sales|reception|follow-up|referral|conversion|seo|website-analytics/, '📣'],
  [/notification|bildirishnoma|bell|alert/, '🔔'],
  [/task|vazifa|mission|assignment|homework|topshiriq/, '📋'],
  [/game|o'yin|oyin|mini-games|lucky-wheel|tournament|1v1|team-battles/, '🎮'],
  [/first-aid|emergency|tibbiy|health/, '🩹'],
  [/transport/, '🚌'],
  [/cafeteria|oshxona/, '🍽️'],
  [/inventory|asset|equipment|jihoz|procurement/, '📦'],
  [/backup|database|data-export|data-import|migration/, '💾'],
  [/map\b|xarita/, '🗺️'],
  [/shop|marketplace|store/, '🛍️'],
  [/streak|flame|fire/, '🔥'],
  [/vip|crown/, '👑'],
  [/birthday|tug'ilgan/, '🎂'],
  [/diary|kundalik/, '📔'],
  [/podcast/, '🎙️'],
  [/whiteboard/, '🖊️'],
  [/qr-/, '🔳'],
  [/newsletter|email-template/, '📧'],
  [/sms/, '📲'],
  [/phone|telefon/, '☎️'],
  [/vot|poll|saylov/, '🗳️'],
  [/idea|g'oya|lightbulb|innovation/, '💡'],
  [/calc/, '🧮'],
  [/student|o'quvchi|alumni|active-students/, '🎓'],
  [/teacher|o'qituvchi|mentorship/, '👨‍🏫'],
  [/parent|ota-ona/, '👨‍👩‍👧'],
  [/olympiad|olimpiad/, '🥇'],
  [/debate|speaking-club/, '🗣️'],
  [/curriculum|o'quv-reja|lesson|dars/, '📖'],
];

const GROUP_FALLBACK = {
  'Command Center': '🏠',
  'Akademik': '🎓',
  "O'quv jarayoni": '📖',
  "O'quvchi boshqaruvi": '👥',
  'Moliya': '💰',
  'Marketing & CRM': '📣',
  'Boshqaruv & HR': '🏢',
  'Aloqa & Gamifikatsiya': '🎮',
  'Tizim & IT': '⚙️',
};

export function emojiForItem(item, groupName) {
  const hay = `${item.key} ${item.label}`.toLowerCase();
  for (const [re, emoji] of RULES) {
    if (re.test(hay)) return emoji;
  }
  return GROUP_FALLBACK[groupName] || '📌';
}
